version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: fav-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: favdb
      MYSQL_USER: app
      MYSQL_PASSWORD: app123
      # 設置編碼解決亂碼問題
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./DB/DDL.sql:/docker-entrypoint-initdb.d/01-DDL.sql
      - ./DB/DML.sql:/docker-entrypoint-initdb.d/02-DML.sql
      - ./DB/StoredProcedures.sql:/docker-entrypoint-initdb.d/03-StoredProcedures.sql
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --init-connect='SET NAMES utf8mb4'
      --default-time-zone='+08:00'
    networks:
      - fav-network

  adminer:
    image: adminer:latest
    container_name: fav-adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
      - fav-network
    depends_on:
      - db

volumes:
  mysql_data:

networks:
  fav-network:
    driver: bridge
